### ISSUE TITLE
atom-text-editor scrollable in Y direction

### ISSUE THREAD

**Issue by HoverBaum** [jmcalaway/atom-genesis-ui#5]
All `<atom-test-editor>` tags are scrolling in Y direction.

Aparently Atom has a padding left and top on these elements and the child gets pushed so far down, that the input starts to be scrollable in Y direction. Removing the padding top will fix this. However this is in contrast to all other seems. So far I have only seen themes that have the padding top and the cursor touch the bottom border.

Not sure where the theme should go but having all inputs scroll is definitely weird.

Here is an image of what I am talking about:
![weirdscrolls](https://cloud.githubusercontent.com/assets/7557414/14348565/f0366bda-fcef-11e5-9bd1-0a880866254c.png)

I am on Atom 1.6.2 without anything in my personal stylesheet.

**Comment by HoverBaum** [comment]
Just realized, this is actually an isse with the Syntax theme and not the UI theme. Works just fine if you use a different syntax theme.

**Comment by jeffcalaway** [comment]
Hendrik,
Thanks for your feedback! For whatever reason, there was a max-height restriction causing the scrolling. I've since added padding to the bottom and removed the max-height. Hopefully I didn't undo anything I did that had purpose, but I'll keep an eye on it. Meanwhile, this should be fixed for you.

Thank you!
